### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by myffs** [MMbay64/V.S.-Stupid-2.5-Fnf-Mod#2]

**Comment by myffs** [comment]
...

**Comment by MMbay64** [comment]
How??

**Comment by myffs** [comment]
![StupidNor_Assets](https://user-images.githubusercontent.com/113801267/209471214-ea083e01-c016-4bff-8454-e8f53a6d222f.png)

made a new one dumbass

**Comment by MMbay64** [comment]
Ok
